# cloudbuild.yaml

steps:
  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/apigee-example-cicd:latest', 'apigee-example/']
    # Replace 'image-name:tag' with your desired image name and tag.

  # Step to run the Docker container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '-p', '8080:80', 'gcr.io/$PROJECT_ID/apigee-example-cicd:latest']
    # Replace '8080:80' with your desired port mapping. 
    # Replace 'image-name:tag' with the image name and tag used in the previous step.
